# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Gradle Build and Artifact Upload

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          architecture: x64
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Build with Gradle
        uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
        env:
          HEM_HEDERA_OPERATOR_ID: ${{secrets.operatorId}}
          HEM_HEDERA_PRIVATE_KEY: ${{secrets.operatorKey}}
          HEM_HEDERA_OFFSETS_CONTRACT_ID: ${{secrets.contractId}}
        with:
          arguments: build
      - uses: actions/upload-artifact@v3
        with:
          name: Build Artifacts
          path: |
            **/build/libs
            **/build/reports